//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mails", typeof(Mails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted to group.
        /// </summary>
        public static string AcceptedToGroup {
            get {
                return ResourceManager.GetString("AcceptedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0}&lt;/b&gt;, &lt;b&gt;{1}&lt;/b&gt; has just been added to group &lt;b&gt;{2}&lt;/b&gt;.
        ///&lt;br /&gt;
        ///&lt;b&gt;Հարգելի {0}, {1} ընդգրկվել է {2} խմբում։&lt;/b&gt;
        ///&lt;br /&gt;
        ///{3}.
        /// </summary>
        public static string AcceptedToGroupBody {
            get {
                return ResourceManager.GetString("AcceptedToGroupBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Created.
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account was just created using your mail
        ///&lt;br /&gt;
        ///&lt;b&gt;Ձեր էլ․ հասցեի օգտագործմամբ, իրականացվել է օգտատիրոջ գրանցում։&lt;/b&gt;.
        /// </summary>
        public static string AccountCreatedBody {
            get {
                return ResourceManager.GetString("AccountCreatedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child added.
        /// </summary>
        public static string ChildAdded {
            get {
                return ResourceManager.GetString("ChildAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0}&lt;/b&gt;, You have just added a child &lt;b&gt;{1}&lt;/b&gt;.
        ///&lt;br /&gt;
        ///&lt;b&gt;Հարգելի {0}&lt;/b&gt;, դուք գրանցեցիք &lt;b&gt;{1}&lt;/b&gt;:.
        /// </summary>
        public static string ChildAddedBody {
            get {
                return ResourceManager.GetString("ChildAddedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your account.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by clicking &lt;a href=&apos;{0}&apos;&gt;here&lt;/a&gt;
        ///&lt;br /&gt;
        ///&lt;b&gt;Խնդրում ենք հաստատել ձեր գրանցումը սեղմելով &lt;a href=&apos;{0}&apos;&gt;այստեղ&lt;/a&gt;:&lt;/b&gt;.
        /// </summary>
        public static string ConfirmAccountBody {
            get {
                return ResourceManager.GetString("ConfirmAccountBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} is full.
        /// </summary>
        public static string GroupIsFull {
            get {
                return ResourceManager.GetString("GroupIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0}&lt;/b&gt;, the group &lt;b&gt;{1}&lt;/b&gt; to which &lt;b&gt;{2}&lt;/b&gt; is joined is full and is ready to start
        ///&lt;br /&gt;
        ///&lt;b&gt;Հարգելի {0}, խումբ {1} ձևավորված է և պատրաստ է մեկնարկման։&lt;/b&gt;.
        /// </summary>
        public static string GroupIsFullBody {
            get {
                return ResourceManager.GetString("GroupIsFullBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Dear {0}&lt;/b&gt;, your password has been changed.
        ///&lt;br /&gt;
        ///&lt;b&gt;Հարգելի {0}&lt;/b&gt;, Ձեր գաղտնաբառը փոխված է։.
        /// </summary>
        public static string PasswordChangedBody {
            get {
                return ResourceManager.GetString("PasswordChangedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking &lt;a href=&apos;{0}&apos;&gt;here&lt;/a&gt;
        ///&lt;br /&gt;
        ///&lt;b&gt;Գաղտնաբառը փոխելու համար սեղմեք &lt;a href=&apos;{0}&apos;&gt;այստեղ&lt;/a&gt;:&lt;/b&gt;.
        /// </summary>
        public static string ResetPasswordBody {
            get {
                return ResourceManager.GetString("ResetPasswordBody", resourceCulture);
            }
        }
    }
}
