//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CetCources.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayHours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DayHours()
        {
            this.Inactive = false;
            this.FreeHours = new HashSet<FreeHour>();
        }
    
        public int DayHourId { get; set; }
        public int DayOfWeek { get; set; }
        public int BaseHourId { get; set; }
        public bool Inactive { get; set; }
    
        public virtual BaseHours BaseHours { get; set; }
        public virtual DayOfWeek TheDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreeHour> FreeHours { get; set; }
    }
}
