//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CetCources.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeHour
    {
        public int FreeHourId { get; set; }
        public int ChildId { get; set; }
        public int DayHourId { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual DayHours DayHours { get; set; }
    }
}
