//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CetCources.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Children = new HashSet<Child>();
        }
    
        public int GroupId { get; set; }
        public Nullable<int> FreqId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> PersonCount { get; set; }
        public bool Inactive { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public Nullable<int> Sunday { get; set; }
        public Nullable<int> Monday { get; set; }
        public Nullable<int> Tuesday { get; set; }
        public Nullable<int> Wednesday { get; set; }
        public Nullable<int> Thursday { get; set; }
        public Nullable<int> Friday { get; set; }
        public Nullable<int> Saturday { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> EduLevel { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Trainer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Children { get; set; }
        public virtual CourseFrequency CourseFrequency { get; set; }
        public virtual YearGroup YearGroups { get; set; }
        public virtual HourShifts HourShifts_Sun { get; set; }
        public virtual HourShifts HourShifts_Mon { get; set; }
        public virtual HourShifts HourShifts_Tue { get; set; }
        public virtual HourShifts HourShifts_Wed { get; set; }
        public virtual HourShifts HourShifts_Thu { get; set; }
        public virtual HourShifts HourShifts_Fri { get; set; }
        public virtual HourShifts HourShifts_Sat { get; set; }
    }
}
