//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CetCources.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class qExportData
    {
        public int ChildId { get; set; }
        public System.DateTime Child_Creation_Date { get; set; }
        public string Parent_Full_Name { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Children_Full_Name { get; set; }
        public string Birth_Date { get; set; }
        public string Year_Group_Name { get; set; }
        public string EduGroupName { get; set; }
        public string Frequency_Description { get; set; }
        public string School_Name { get; set; }
        public int ClassNo { get; set; }
        public int Edu_Level { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
        public string Sunday { get; set; }
        public string Trainer { get; set; }
        public bool Inactive { get; set; }
        public string Child_Related_Comment { get; set; }
        public string Parent_Related_Comment { get; set; }
        public bool Terms_Accepted { get; set; }
    }
}
